import { Jost } from 'next/font/google'
import './globals.css'

const jost = Jost({ 
  weight: ['400', '600'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
 })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='h-full bg-primary'>
      <body className={jost.className}>



        <main className='relative flex flex-col min-h-screen '>
          <div className='flex-grow flex-1'>{children}</div>
        </main>



      </body>
    </html>
  )
}
